memory_size: 6024
number_cpus: 1
box: "puppetlabs/centos-6.5-64-nocm"
repo: "http://bigtop01.cloudera.org:8080/view/Releases/job/Bigtop-0.8.0/label=centos6/6/artifact/output/"
num_instances: 1
components: "hadoop,yarn,mapred-app,tachyon"
