options:
    resources_mirror:
        type: string
        default: ''
        description: |
            URL used to fetch resources (e.g., Hadoop binaries) instead of the
            location specified in resources.yaml.
    spark_bench_enabled:
        type: boolean
        default: true
        description: |
            When set to 'true' (the default), this charm will download and
            install the SparkBench benchmark suite from the configured URLs.
            When set to 'false', SparkBench will be removed from the unit,
            though any data stored in hdfs:///user/ubuntu/spark-bench will be
            preserved.
    spark_bench_ppc64le:
        type: string
        default: 'https://s3.amazonaws.com/jujubigdata/ibm/noarch/spark-bench-2.0-20151214-ffb72f23.tgz#sha256=ffb72f233eaafccef4dda6d4516f23e043d1b14b9d63734211f4d1968db86a3c'
        description: |
            URL (including hash) of a ppc64le tarball of SparkBench. By
            default, this points to a pre-built SparkBench binary based on
            sources in the upstream repository. This option is only valid when
            'spark_bench_enabled' is 'true'.
    spark_bench_x86_64:
        type: string
        default: 'https://s3.amazonaws.com/jujubigdata/ibm/noarch/spark-bench-2.0-20151214-ffb72f23.tgz#sha256=ffb72f233eaafccef4dda6d4516f23e043d1b14b9d63734211f4d1968db86a3c'
        description: |
            URL (including hash) of an x86_64 tarball of SparkBench. By
            default, this points to a pre-built SparkBench binary based on
            sources in the upstream repository. This option is only valid when
            'spark_bench_enabled' is 'true'.
    spark_execution_mode:
        type: string
        default: 'standalone'
        description: |
            Options are "local", "standalone", "yarn-client", and
            "yarn-cluster". Consult the readme for details on these options.
