docker:
        memory_size: "2048"
        image: "bigtop/ssh:centos-6.4"

boot2docker:
        memory_size: "4196"
        number_cpus: "2"

repo: "http://bigtop01.cloudera.org:8080/view/Releases/job/Bigtop-0.8.0/label=centos6/6/artifact/output/"
components: "hadoop,yarn"
namenode_ui_port: "50070"
yarn_ui_port: "8088"
hbase_ui_port: "60010"
