docker:
        memory_size: "2048"
        image:  "debian:jessie"

boot2docker:
        memory_size: "4196"
        number_cpus: "2"

repo: "http://to.do/notyet"
distro: debian
components: [hadoop, yarn]
namenode_ui_port: "50070"
yarn_ui_port: "8088"
hbase_ui_port: "60010"
